DROP TABLE IF EXISTS PROFILES;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE PROFILES (
  PROF_ID UUID DEFAULT uuid_generate_v4 (),
  PROF_TAG VARCHAR(200) NOT NULL UNIQUE,
  PROF_NAME VARCHAR(200) NOT NULL,
  CONSTRAINT PK_PROF PRIMARY KEY (PROF_ID)
);