DROP TABLE IF EXISTS PROJECT;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE PROJECT (
  PROJ_ID UUID DEFAULT uuid_generate_v4 (),
  PROJ_NAME VARCHAR(200) NOT NULL UNIQUE,
  PROJ_USER UUID NOT NULL,
  PROJ_DESCRIPTION VARCHAR(200) NOT NULL,
  CONSTRAINT PK_PROJ PRIMARY KEY (PROJ_ID),
  CONSTRAINT FK_PROJ_USER FOREIGN KEY (PROJ_USER) REFERENCES USERS (USER_ID) ON DELETE CASCADE
);