DROP TABLE IF EXISTS USERS;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE USERS (
  USER_ID UUID DEFAULT uuid_generate_v4 (),
  PROF_ID UUID NOT NULL,
  USER_NAME VARCHAR(200) NOT NULL,
  USER_CPF VARCHAR(15) NOT NULL UNIQUE,
  USER_EMAIL VARCHAR(200) NOT NULL UNIQUE,
  USER_PASSWORD VARCHAR(200) NOT NULL,
  CONSTRAINT PK_USER PRIMARY KEY (USER_ID),
  CONSTRAINT FK_USER_PROF FOREIGN KEY (PROF_ID) REFERENCES PROFILES (PROF_ID) ON DELETE CASCADE
);